version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: marathi_chatbot_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

  api:
    build: ./API
    container_name: marathi_chatbot_api
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    volumes:
      - ./API:/app
    restart: unless-stopped

volumes:
  redis_data: