@echo off
echo Starting Marathi Startup Chatbot...
cd /d "d:\SM\API"
echo Installing dependencies...
pip install -r requirements.txt
echo Starting the server...
uvicorn main:app --reload --host 0.0.0.0 --port 8000
pause